import { v4 as uuid } from 'uuid';

export const users = [
    {
        id: uuid(),
        avatarUrl: '/avatars/avatar_3.png',
        workingTime: '1:30',
        Name: 'Ekaterina Tankova',
        Noice_Level: 'unsafe',
        Vibration_Level: 'unsafe',
        Temperature: '30C',
        phone: '304-428-3097',
        connectionStatus: 'connected'
    },
    {
        id: uuid(),
        avatarUrl: '/avatars/avatar_4.png',
        workingTime: '2:45',
        Name: 'Cao Yu',
        Noice_Level: 'safe',
        Vibration_Level: 'safe',
        Temperature: '28C',
        phone: '712-351-5711',
        connectionStatus: 'connected'
    },
    {
        id: uuid(),
        avatarUrl: '/avatars/avatar_2.png',
        workingTime: '4:10',
        Name: 'Alexa Richardson',
        Noice_Level: 'safe',
        Temperature: '30C',
        Vibration_Level: 'unsafe',
        phone: '770-635-2682',
        connectionStatus: 'disconnected'
    }
    // {
    //   id: uuid(),
    //   address: {
    //     country: "USA",
    //     state: "Ohio",
    //     city: "Dover",
    //     street: "4158  Hedge Street",
    //   },
    //   avatarUrl: "/static/images/avatars/avatar_5.png",
    //   createdAt: 1554930000000,
    //   workingTime: "anje.keizer@devias.io",
    //   Name: "Anje Keizer",
    //   phone: "908-691-3242",
    // },
    // {
    //   id: uuid(),
    //   address: {
    //     country: "USA",
    //     state: "Texas",
    //     city: "Dallas",
    //     street: "75247",
    //   },
    //   avatarUrl: "/static/images/avatars/avatar_6.png",
    //   createdAt: 1554757200000,
    //   workingTime: "clarke.gillebert@devias.io",
    //   Name: "Clarke Gillebert",
    //   phone: "972-333-4106",
    // },
    // {
    //   id: uuid(),
    //   address: {
    //     country: "USA",
    //     state: "California",
    //     city: "Bakerfield",
    //     street: "317 Angus Road",
    //   },
    //   avatarUrl: "/static/images/avatars/avatar_1.png",
    //   createdAt: 1554670800000,
    //   workingTime: "adam.denisov@devias.io",
    //   Name: "Adam Denisov",
    //   phone: "858-602-3409",
    // },
    // {
    //   id: uuid(),
    //   address: {
    //     country: "USA",
    //     state: "California",
    //     city: "Redondo Beach",
    //     street: "2188  Armbrester Drive",
    //   },
    //   avatarUrl: "/static/images/avatars/avatar_7.png",
    //   createdAt: 1554325200000,
    //   workingTime: "ava.gregoraci@devias.io",
    //   Name: "Ava Gregoraci",
    //   phone: "415-907-2647",
    // },
    // {
    //   id: uuid(),
    //   address: {
    //     country: "USA",
    //     state: "Nevada",
    //     city: "Las Vegas",
    //     street: "1798  Hickory Ridge Drive",
    //   },
    //   avatarUrl: "/static/images/avatars/avatar_8.png",
    //   createdAt: 1523048400000,
    //   workingTime: "emilee.simchenko@devias.io",
    //   Name: "Emilee Simchenko",
    //   phone: "702-661-1654",
    // },
    // {
    //   id: uuid(),
    //   address: {
    //     country: "USA",
    //     state: "Michigan",
    //     city: "Detroit",
    //     street: "3934  Wildrose Lane",
    //   },
    //   avatarUrl: "/static/images/avatars/avatar_9.png",
    //   createdAt: 1554702800000,
    //   workingTime: "kwak.seong.min@devias.io",
    //   Name: "Kwak Seong-Min",
    //   phone: "313-812-8947",
    // },
    // {
    //   id: uuid(),
    //   address: {
    //     country: "USA",
    //     state: "Utah",
    //     city: "Salt Lake City",
    //     street: "368 Lamberts Branch Road",
    //   },
    //   avatarUrl: "/static/images/avatars/avatar_10.png",
    //   createdAt: 1522702800000,
    //   workingTime: "merrile.burgett@devias.io",
    //   Name: "Merrile Burgett",
    //   phone: "801-301-7894",
    // },
];
